on:
  push:
    branches:
      - master




jobs:
  build:
    run-on: ubuntu-latest

    steps:
      - name: 'Testing Github action'
        run: pwd

      - name: 'Testing Github action'
        run: echo Os1